const data = [
  {
    id: 1,
    skill_name: ['Front-end', 'Developer'],
    img: 'https://edubaba-org.vercel.app/first.svg',
    skills: [
      'HTML / CSS3',
      'JavaScript (ES6)',
      'ReactJS',
      'NextJS',
      'TailwindCSS',
      'Bootstrap',
      'REST API / GraphQL',
    ],
  },
  {
    id: 2,
    skill_name: ['Back-end', 'Developer'],
    img: 'https://edubaba-org.vercel.app/second.svg',
    skills: [
      'NodeJS / Express.js',
      'MongoDB / MySQL / MSSQL',
      'Next.js (API)',
      'PHP',
      'WordPress Theme Dev',
      'WordPress Plugin Dev',
      'ASP (Once upon a time)',
    ],
  },
  {
    id: 3,
    skill_name: ['Language'],
    img: 'https://edubaba-org.vercel.app/third.svg',
    skills: ['C/C++', 'HTML', 'JavaScript'],
  },
  {
    id: 4,
    skill_name: 'Quinn',
    img: 'https://edubaba-org.vercel.app/fourth.svg',
    skills: [
      'HTML5',
      'CSS3',
      'JavaScript',
      'React',
      'Angular',
      'Vue.js',
      'Responsive Web Design',
      'Sass/Less',
      'Webpack',
    ],
  },
  {
    id: 5,
    skill_name: 'Cooper',
    img: 'https://edubaba-org.vercel.app/fifth.svg',
    skills: [
      'HTML5',
      'CSS3',
      'JavaScript',
      'React',
      'Angular',
      'Vue.js',
      'Responsive Web Design',
      'Sass/Less',
      'Webpack',
    ],
  },
  {
    id: 6,

    skill_name: 'Juditha',
    img: 'https://edubaba-org.vercel.app/sisxth.svg',
    skills: [
      'HTML5',
      'CSS3',
      'JavaScript',
      'React',
      'Angular',
      'Vue.js',
      'Responsive Web Design',
      'Sass/Less',
      'Webpack',
    ],
  },
];
export default data;
